file_name: '/Users/sarinaxi/Desktop/Thesis/StudentTeacherBERT/data/all_data.pkl'
Student:
    folder: 'StudentTeacherBERT/results/test_student_gru'
    name: 'test_student_gru.pt'
    dropout: 0.05
    input_size: 50
    lr: 0.0002
    batch_size: 16
    splits: 0.3
    epochs: 50
    hidden_size: 20
  
Teacher:
    architecture: 'bert-base-uncased'
    folder: 'StudentTeacherBERT/results/test_student'
    name: 'test_student.pt'
    dropout: 0.05
    input_size: 50
    lr: 0.0001
    batch_size: 16
    splits: 0.4
    epochs: 10
    hidden_size: 15
    
StudentTeacher:
    folder: 'StudentTeacherBERT/results/test_student_teacher'
    name: 'test_student_teacher.pt'
    dropout: 0.05
    lr: 0.0005
    batch_size: 16
    splits: 0.3
    epochs: 10
