spamDetector:
    dropout: 0.03
    lr: 0.0005
    batch_size: 32
    splits: 0.4
    epochs: 10
    data_file: 'data/smsSpam/SMSSpamCollection.txt'
    index: -2
    architecture: 'gpt'
    sms: False
    easy: True
prompting:
    k: 0