spamDetector:
    dropout: 0.01
    lr: 0.0008
    batch_size: 16
    splits: 0.4
    epochs: 15
    data_file: 'data/smsSpam/SMSSpamCollection.txt'
    index: -2
    architecture: 'gpt'
    sms: False
    easy: True
prompting:
    k: 0