spamDetector:
    dropout: 0.01
    lr: 0.0008
    batch_size: 16
    splits: 0.4
    epochs: 3
    data_file: 'SpamDetector/data/smsSpam/SMSSpamCollection.txt'
    index: -2
    architecture: 'bert'
    sms: True
    easy: True
prompting:
    k: 0