file_name: '/Users/sarinaxi/Desktop/Thesis/SpamDetector/data/smsSpam/SMSSpamCollection.txt'
StudentPT:
    folder: 'StudentTeacher/results/StudentPreTrain'
    name: 'student.pt'
    dropout: 0.1
    lr: 0.0009
    splits: 0.2
    epochs: 20
    downsample: True

    input_size: 40
    vocab_size: 1000
    batch_size: 16
    hidden_size: 10
    embed_size: 20
    
TeacherPT:
    folder: 'StudentTeacher/results/TeacherTestCombo2'
    name: 'teacher.pt'
    dropout: 0.2
    lr: 0.0005
    splits: 0.5
    epochs: 30
    downsample: True

    input_size: 40
    vocab_size: 1000
    batch_size: 16
    hidden_size: 10
    embed_size: 20
    
StudentTeacher:
    folder: 'StudentTeacher/results/test_student_teacher'
    name: 'test_student_teacher.pt'
    factor: 10
    dropout: 0.2
    lr: 0.0005
    batch_size: 16
    splits: 0.3
    epochs: 30

    input_size: 40
    vocab_size: 1000
    hidden_size: 10
    downsample: False
