file_name: '/Users/sarinaxi/Desktop/Thesis/StudentTeacher/data/all_data.pkl'
Student:
    folder: 'StudentTeacher/results/test_student'
    name: 'test_student.pt'
    dropout: 0.05
    input_size: 25
    lr: 0.0001
    batch_size: 16
    splits: 0.4
    epochs: 50
    hidden_size: 15
  
Teacher:
    architecture: 'bert-base-uncased'
    folder: 'StudentTeacher/results/test_teacher_2'
    name: 'test_teacher.pt'
    dropout: 0.01
    input_size: 25
    lr: 0.0005
    batch_size: 32
    splits: 0.3
    epochs: 10
    
StudentTeacher:
    folder: 'StudentTeacher/results/test_student_teacher'
    name: 'test_student_teacher.pt'
    dropout: 0.05
    lr: 0.0005
    batch_size: 16
    splits: 0.3
    epochs: 10
