file_name: '/Users/sarinaxi/Desktop/Thesis/SpamDetector/data/smsSpam/SMSSpamCollection.txt'
StudentPT:
    folder: 'StudentTeacher/results/sentiment'
    name: 'student.pt'
    dropout: 0.1
    lr: 0.0008
    splits: 0.25
    epochs: 7
    downsample: True

    input_size: 50
    batch_size: 32
    hidden_size: 50
    embed_size: 100
    
TeacherPT:
    folder: 'StudentTeacher/results/sentiment_spam_detector_arch_withL2reg_2_downsample'
    name: 'teacher.pt'
    dropout: 0.2
    lr: 0.0008
    splits: 0.2
    epochs: 20
    downsample: True

    input_size: 50
    batch_size: 32
    hidden_size: 50
    embed_size: 100
    
StudentTeacher:
    folder: 'StudentTeacher/results/TEST3'
    name: 'student_teacher.pt'
    factor: 10
    dropout: 0.2
    lr: 0.0004
    batch_size: 16
    splits: 0.3
    epochs: 50

    input_size: 50
    batch_size: 32
    hidden_size: 50
    embed_size: 100
    downsample: True
    similarity: 'cosine'