file_name: '/Users/sarinaxi/Desktop/Thesis/StudentTeacherGRU/data/all_data.pkl'
Student:
    folder: 'StudentTeacherGRU/results/test_student_gru'
    name: 'test_student_gru.pt'
    dropout: 0.2
    input_size: 40
    lr: 0.0002
    batch_size: 16
    splits: 0.3
    epochs: 30
    hidden_size: 10
    embed_size: 20
  
Teacher:
    architecture: 'bert-base-uncased'
    folder: 'StudentTeacherGRU/results/test_student'
    name: 'test_student.pt'
    dropout: 0.05
    input_size: 50
    lr: 0.0001
    batch_size: 16
    splits: 0.4
    epochs: 10
    hidden_size: 15
    
StudentTeacher:
    folder: 'StudentTeacherGRU/results/test_student_teacher'
    name: 'test_student_teacher.pt'
    dropout: 0.05
    lr: 0.0005
    batch_size: 16
    splits: 0.3
    epochs: 10
