file_name: '/Users/sarinaxi/Desktop/Thesis/SpamDetector/data/smsSpam/SMSSpamCollection.txt'
Student:
    folder: 'StudentTeacherGRU/results/StudentPT70%EarlyStop'
    name: 'student.pt'
    dropout: 0.1
    input_size: 40
    lr: 0.0009
    vocab_size: 1000
    batch_size: 16
    splits: 0.2
    epochs: 60
    hidden_size: 10
    embed_size: 20
    downsample: True
  
Teacher:
    folder: 'StudentTeacherGRU/results/TeacherPT'
    name: 'teacher.pt'
    dropout: 0.2
    input_size: 40
    lr: 0.0005
    vocab_size: 1000
    batch_size: 16
    splits: 0.3
    epochs: 30
    hidden_size: 10
    embed_size: 20
    downsample: False
    
StudentTeacher:
    folder: 'StudentTeacherGRU/results/test_student_teacher'
    name: 'test_student_teacher.pt'
    dropout: 0.05
    lr: 0.0005
    batch_size: 16
    splits: 0.3
    epochs: 10
